### ISSUE TITLE
NetMngr exception not handled in controller

### ISSUE THREAD

**Issue by jkleinerman** [kleinerman/dobie#17]
On some situation when controller loses connection with server the following exception happens:

Nov 01 09:36:29 alarmpi env[273]: Exception in thread EventMngr:
Nov 01 09:36:29 alarmpi env[273]: Traceback (most recent call last):
Nov 01 09:36:29 alarmpi env[273]:   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
Nov 01 09:36:29 alarmpi env[273]:     self.run()
Nov 01 09:36:29 alarmpi env[273]:   File "/home/jkleinerman/dobie/controller/py_src/events.py", line 70, in run
Nov 01 09:36:29 alarmpi env[273]:     self.netMngr.sendEvent(event)
Nov 01 09:36:29 alarmpi env[273]:   File "/home/jkleinerman/dobie/controller/py_src/network.py", line 216, in sendEvent
Nov 01 09:36:29 alarmpi env[273]:     self.sendToServer(msg)
Nov 01 09:36:29 alarmpi env[273]:   File "/home/jkleinerman/dobie/controller/py_src/network.py", line 183, in sendToServer
Nov 01 09:36:29 alarmpi env[273]:     self.netPoller.modify(self.srvSock, select.POLLOUT)
Nov 01 09:36:29 alarmpi env[273]: ValueError: file descriptor cannot be a negative integer (-1)

**Comment by jkleinerman** [comment]
The problem was solved in commit: 154b01dfcc7f3f0f6550077ccaf5299c505ee8db in jek_srv_bcknd
